services:
  db:
    image: postgres:16
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      GODRINK_CORS: "http://localhost:8081"
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:
