services:
  db:
    image: postgres:16
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    image: ghcr.io/port39/go-drink:latest
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:
