services:
  db:
    image: postgres:16
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  app:
    build:
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      GODRINK_CORS: "http://localhost:8081"
      GODRINK_DBDRIVER: ${GODRINK_DBDRIVER}
      GODRINK_DB: ${GODRINK_DB}
      GODRINK_SMTPHOST: ${GODRINK_SMTPHOST}
      GODRINK_SMTPUSER: ${GODRINK_SMTPUSER}
      GODRINK_SMTPPASS: ${GODRINK_SMTPPASS}
      GODRINK_SMTPFROM: ${GODRINK_SMTPFROM}
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:
