name: Docker
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "docker-compose.yaml"
      - "docker-compose.dev.yaml"
      - "openapi.yaml"
      - ".run"
      - "http-test"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/port39/go-drink:latest
