name: http-test.yml
on:
  push:
    branches:
      - "*"

jobs:
  HTTP-Tests:
    permissions:
      contents: read
      actions: read
      checks: write
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: "changeme"
          POSTGRES_USER: "godrink"
          POSTGRES_DB: "godrink"
        ports:
          - "5432:5432"
        volumes:
          - pgdata:/var/lib/postgresql/data
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Go
        uses: actions/setup-go@v5.0.2
      - name: Run Go-Drink
        env:
          GODRINK_DB: postgresql://godrink:changeme@localhost:5432/godrink?sslmode=disable
        run: "go run . &"
      - name: Execute HTTP requests
        run: ./http-test/test.sh
        timeout-minutes: 3
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          detailed_summary: true
          include_passed: true
          require_passed_tests: true
          update_check: true
          report_paths: ./http-test-reports/report.xml
      - name: Upload Test results
        uses: actions/upload-artifact@v4.3.4
        with:
          name: http-test-reports
          path: ./http-test-reports/report.xml
